# Generated by Django 3.0.6 on 2020-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countnumbers',
            name='blankets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countnumbers',
            name='blood_camps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countnumbers',
            name='organs',
            field=models.IntegerField(default=0),
        ),
    ]
