# Generated by Django 3.0.6 on 2020-06-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200626_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=260)),
                ('name', models.CharField(max_length=260)),
            ],
        ),
    ]
